/**
 * @author Ayush Garg
 * @date 2026-01-15
 * @brief Unit tests for the filesystem module.
 *
 * Unit tests for the filesystem module.
 * Note most of these were generated by Claude Opus 4.5.
 */

#include "filesys.h"

// Helper macro for test assertions with error messages
#define TEST_ASSERT(cond, msg)                                                 \
    do                                                                         \
    {                                                                          \
        if (!(cond))                                                           \
        {                                                                      \
            LOG_ERROR("ASSERTION FAILED: %s\n", msg);                          \
            return -1;                                                         \
        }                                                                      \
    } while (0)

// Helper function to initialize a clean filesystem for testing
inline static int filesys_test_setup_clean_filesystem(slate_t *slate)
{
    lfs_ssize_t code = filesys_reformat_initialize(slate);
    if (code < 0)
    {
        LOG_ERROR("Failed to reformat filesystem for test setup: %d\n", code);
        return -1;
    }

    return 0;
}

// Helper function to write a really big file into filesys
// This should be used after a lot of other tests to make sure that
// writing to buffer and writing to mram works.
int8_t filesys_test_write_whole_buffer(slate_t *slate, uint8_t *buffer,
                                       FILESYS_BUFFERED_FILE_LEN_T len)
{
    for (FILESYS_BUFFER_SIZE_T i = 0; i < len; i += FILESYS_BUFFER_SIZE)
    {
        const FILESYS_BUFFER_SIZE_T to_write =
            (len - i) < FILESYS_BUFFER_SIZE ? (len - i) : FILESYS_BUFFER_SIZE;
        LOG_DEBUG("Writing %u bytes at offset %u\n", to_write, i);

        int8_t code =
            filesys_write_data_to_buffer(slate, buffer + i, to_write, 0);
        TEST_ASSERT(code == FILESYS_OK, "File buffer write should succeed");

        code = filesys_write_buffer_to_mram(slate, to_write);
        TEST_ASSERT(code == FILESYS_OK,
                    "File buffer to MRAM write should succeed");
    }

    return 0;
}

// ============================================================================
// Test 1: Basic write and readback (original test)
// ============================================================================
int filesys_test_write_readback_success()
{
    LOG_DEBUG("=== Test: Write and Readback ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t res;

    FILESYS_BUFFERED_FNAME_STR_T fname_str = "A3";
    FILESYS_BUFFERED_FILE_CRC_T crc =
        0x100ECE8C; // Precomputed CRC for 0x00..0x3F

    int8_t code =
        filesys_start_file_write(&test_slate, fname_str, 64, crc, &res);

    if (code != FILESYS_OK)
    {
        LOG_ERROR("Failed to start file write for testing: %d\n", code);
        return -1;
    }

    LOG_DEBUG("Returned code from start_file_write: %d\n", code);
    TEST_ASSERT(
        test_slate.filesys_is_writing_file,
        "filesys_is_writing_file should be true after start_file_write");

    uint8_t buffer[64];
    for (uint8_t i = 0; i < 64; i++)
        buffer[i] = i;

    code = filesys_write_data_to_buffer(&test_slate, buffer, sizeof(buffer), 0);

    TEST_ASSERT(code == FILESYS_OK,
                "write_data_to_buffer should write full buffer size");
    TEST_ASSERT(test_slate.filesys_buffer_is_dirty,
                "Buffer should be dirty after write_data_to_buffer");

    code = filesys_write_buffer_to_mram(&test_slate, sizeof(buffer));

    TEST_ASSERT(code == FILESYS_OK,
                "write_buffer_to_mram should write full buffer size");
    TEST_ASSERT(!test_slate.filesys_buffer_is_dirty,
                "Buffer should be clean after write_buffer_to_mram");

    code = filesys_complete_file_write(&test_slate);

    if (code != FILESYS_OK)
    {
        LOG_ERROR("Failed to complete file write for testing: %d\n", code);
        return -1;
    }

    TEST_ASSERT(!test_slate.filesys_is_writing_file,
                "filesys_is_writing_file should be false after "
                "complete_file_write");

    // We do not have read handling in filesys, use LFS!
    int8_t read_buffer[64];
    lfs_file_t read_file;
    lfs_file_opencfg(&test_slate.lfs, &read_file, fname_str, LFS_O_RDONLY,
                     &(struct lfs_file_config){.buffer = cache_buffer});

    lfs_file_read(&test_slate.lfs, &read_file, read_buffer,
                  sizeof(read_buffer));

    lfs_file_close(&test_slate.lfs, &read_file);

    for (size_t i = 0; i < sizeof(read_buffer); i++)
        if (read_buffer[i] != buffer[i])
        {
            LOG_ERROR("Data mismatch at byte %zu: expected %u, got %u\n", i,
                      buffer[i], read_buffer[i]);
            return -1;
        }

    LOG_DEBUG("=== Test PASSED: Write and Readback ===\n");
    return 0;
}

// ============================================================================
// Test 2: Initialize and reformat
// ============================================================================
int filesys_test_initialize_reformat_success()
{
    LOG_DEBUG("=== Test: Initialize and Reformat ===\n");

    slate_t test_slate;

    // Test reformat
    lfs_ssize_t code = filesys_reformat_initialize(&test_slate);
    TEST_ASSERT(code >= 0, "filesys_reformat_initialize should succeed");
    TEST_ASSERT(!test_slate.filesys_is_writing_file,
                "filesys_is_writing_file should be false after reformat");
    TEST_ASSERT(!test_slate.filesys_buffer_is_dirty,
                "filesys_buffer_is_dirty should be false after reformat");

    // Verify filesystem is mounted by checking fs size
    lfs_ssize_t fs_size = lfs_fs_size(&test_slate.lfs);
    TEST_ASSERT(fs_size >= 0, "Filesystem should be accessible after reformat");

    LOG_DEBUG("=== Test PASSED: Initialize and Reformat ===\n");
    return 0;
}

// ============================================================================
// Test 3: Start file write - error when already writing
// ============================================================================
int filesys_test_start_file_write_already_writing_should_fail()
{
    LOG_DEBUG("=== Test: Start File Write - Already Writing ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname1 = "F1";
    FILESYS_BUFFERED_FNAME_STR_T fname2 = "F2";

    // Start first file write
    int8_t code = filesys_start_file_write(&test_slate, fname1, 64, 0x12345678,
                                           &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "First start_file_write should succeed");

    // Try to start a second file write while first is in progress
    code = filesys_start_file_write(&test_slate, fname2, 64, 0x87654321,
                                    &blocks_left);
    TEST_ASSERT(code == FILESYS_ERR_FILE_ALREADY_WRITING,
                "Second start_file_write should fail with "
                "FILESYS_ERR_FILE_ALREADY_WRITING");

    LOG_DEBUG("=== Test PASSED: Start File Write - Already Writing ===\n");
    return 0;
}

// ============================================================================
// Test 4: Write data to buffer - offset and size validation
// ============================================================================
int filesys_test_write_data_to_buffer_bounds_should_fail()
{
    LOG_DEBUG("=== Test: Write Data to Buffer - Bounds Checking ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "BT";

    int8_t code =
        filesys_start_file_write(&test_slate, fname, 256, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    uint8_t small_buffer[16] = {0};

    // Test: Write at offset 0 with valid size
    code = filesys_write_data_to_buffer(&test_slate, small_buffer, 16, 0);
    TEST_ASSERT(code == FILESYS_OK,
                "Writing 16 bytes at offset 0 should succeed");

    // Test: Write exceeding buffer size should fail
    code = filesys_write_data_to_buffer(&test_slate, small_buffer, 16,
                                        FILESYS_BUFFER_SIZE - 8);
    TEST_ASSERT(code == FILESYS_ERR_EXCEED_BUFFER,
                "Writing past buffer boundary should fail with "
                "FILESYS_ERR_EXCEED_BUFFER");

    LOG_DEBUG("=== Test PASSED: Write Data to Buffer - Bounds Checking ===\n");
    return 0;
}

// ============================================================================
// Test 5: Write data to buffer - no file being written
// ============================================================================
int filesys_test_write_data_to_buffer_when_no_file_started_should_fail()
{
    LOG_DEBUG("=== Test: Write Data to Buffer - No File Being Written ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    uint8_t buffer[16] = {0};

    // Try to write to buffer without starting a file write
    int8_t code = filesys_write_data_to_buffer(&test_slate, buffer, 16, 0);
    TEST_ASSERT(code == FILESYS_ERR_NO_FILE_WRITING,
                "Writing to buffer without file write should fail with "
                "FILESYS_ERR_NO_FILE_WRITING");

    LOG_DEBUG(
        "=== Test PASSED: Write Data to Buffer - No File Being Written ===\n");
    return 0;
}

// ============================================================================
// Test 6: Write buffer to MRAM - no file being written
// ============================================================================
int filesys_test_write_buffer_to_mram_when_no_file_started_should_fail()
{
    LOG_DEBUG("=== Test: Write Buffer to MRAM - No File Being Written ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    // Try to write buffer to MRAM without starting a file write
    lfs_ssize_t code = filesys_write_buffer_to_mram(&test_slate, 64);
    TEST_ASSERT(code == FILESYS_ERR_NO_FILE_WRITING,
                "Writing buffer to MRAM without file write should fail with "
                "FILESYS_ERR_NO_FILE_WRITING");

    LOG_DEBUG(
        "=== Test PASSED: Write Buffer to MRAM - No File Being Written ===\n");
    return 0;
}

// ============================================================================
// Test 7: Write buffer to MRAM - clean buffer (no-op)
// ============================================================================
int filesys_test_write_buffer_to_mram_clean_buffer_success()
{
    LOG_DEBUG("=== Test: Write Buffer to MRAM - Clean Buffer ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "CB";

    int8_t code =
        filesys_start_file_write(&test_slate, fname, 64, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // Buffer is clean (not dirty), so write_buffer_to_mram should return 0
    TEST_ASSERT(!test_slate.filesys_buffer_is_dirty,
                "Buffer should be clean after start_file_write");

    code = filesys_write_buffer_to_mram(&test_slate, 64);
    TEST_ASSERT(code == FILESYS_OK,
                "Writing clean buffer should return FILESYS_OK (no-op)");

    LOG_DEBUG("=== Test PASSED: Write Buffer to MRAM - Clean Buffer ===\n");
    return 0;
}

// ============================================================================
// Test 8: Complete file write - buffer is dirty
// ============================================================================
int filesys_test_complete_file_write_dirty_buffer_success()
{
    LOG_DEBUG("=== Test: Complete File Write - Dirty Buffer ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "DB";

    int8_t code =
        filesys_start_file_write(&test_slate, fname, 64, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // Write data to buffer (makes it dirty)
    uint8_t buffer[16] = {1, 2, 3, 4};
    code = filesys_write_data_to_buffer(&test_slate, buffer, 16, 0);
    TEST_ASSERT(code == FILESYS_OK, "write_data_to_buffer should succeed");
    TEST_ASSERT(test_slate.filesys_buffer_is_dirty, "Buffer should be dirty");

    // Try to complete file write with dirty buffer
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_ERR_BUFFER_DIRTY,
                "complete_file_write with dirty buffer should fail with "
                "FILESYS_ERR_BUFFER_DIRTY");

    LOG_DEBUG("=== Test PASSED: Complete File Write - Dirty Buffer ===\n");
    return 0;
}

// ============================================================================
// Test 9: Cancel file write
// ============================================================================
int filesys_test_cancel_file_write_success()
{
    LOG_DEBUG("=== Test: Cancel File Write ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "CA";

    int8_t code =
        filesys_start_file_write(&test_slate, fname, 64, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // Write some data
    uint8_t buffer[32];
    for (int i = 0; i < 32; i++)
        buffer[i] = i;
    code = filesys_write_data_to_buffer(&test_slate, buffer, 32, 0);
    TEST_ASSERT(code == FILESYS_OK, "write_data_to_buffer should succeed");

    // Write buffer to MRAM
    code = filesys_write_buffer_to_mram(&test_slate, 32);
    TEST_ASSERT(code == FILESYS_OK, "First file MRAM write should succeed");

    // Cancel the file write
    code = filesys_cancel_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK, "cancel_file_write should succeed");
    TEST_ASSERT(!test_slate.filesys_is_writing_file,
                "filesys_is_writing_file should be false after cancel");
    TEST_ASSERT(!test_slate.filesys_buffer_is_dirty,
                "Buffer should be clean after cancel");

    // Verify file was deleted (try to open it)
    lfs_file_t file;
    int err =
        lfs_file_opencfg(&test_slate.lfs, &file, fname, LFS_O_RDONLY,
                         &(struct lfs_file_config){.buffer = cache_buffer});
    TEST_ASSERT(err < 0, "File should not exist after cancel_file_write");

    LOG_DEBUG("=== Test PASSED: Cancel File Write ===\n");
    return 0;
}

// ============================================================================
// Test 10: Cancel file write - no file being written
// ============================================================================
int filesys_test_cancel_file_write_no_file_should_fail()
{
    LOG_DEBUG("=== Test: Cancel File Write - No File Being Written ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    // Try to cancel without starting a file write
    int8_t code = filesys_cancel_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_ERR_NO_FILE_WRITING,
                "cancel_file_write without file should fail with "
                "FILESYS_ERR_NO_FILE_WRITING");

    LOG_DEBUG(
        "=== Test PASSED: Cancel File Write - No File Being Written ===\n");
    return 0;
}

// ============================================================================
// Test 11: Clear buffer
// ============================================================================
int filesys_test_clear_buffer_success()
{
    LOG_DEBUG("=== Test: Clear Buffer ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "CL";

    int8_t code =
        filesys_start_file_write(&test_slate, fname, 64, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // Write data to make buffer dirty
    uint8_t buffer[16] = {0};
    code = filesys_write_data_to_buffer(&test_slate, buffer, 16, 0);
    TEST_ASSERT(code == FILESYS_OK, "write_data_to_buffer should succeed");
    TEST_ASSERT(test_slate.filesys_buffer_is_dirty, "Buffer should be dirty");

    // Clear the buffer
    filesys_clear_buffer(&test_slate);
    TEST_ASSERT(!test_slate.filesys_buffer_is_dirty,
                "Buffer should be clean after clear_buffer");

    LOG_DEBUG("=== Test PASSED: Clear Buffer ===\n");
    return 0;
}

// ============================================================================
// Test 12: CRC verification - correct CRC
// ============================================================================
int filesys_test_crc_correct_success()
{
    LOG_DEBUG("=== Test: CRC Verification - Correct CRC ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "CR";
    // CRC32 for bytes 0x00..0x3F (64 bytes)
    FILESYS_BUFFERED_FILE_CRC_T correct_crc = 0x100ECE8C;

    int8_t code = filesys_start_file_write(&test_slate, fname, 64, correct_crc,
                                           &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    uint8_t buffer[64];
    for (uint8_t i = 0; i < 64; i++)
        buffer[i] = i;

    code = filesys_write_data_to_buffer(&test_slate, buffer, 64, 0);
    TEST_ASSERT(code == FILESYS_OK, "write_data_to_buffer should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 64);
    TEST_ASSERT(code == FILESYS_OK,
                "write_buffer_to_mram should write 64 bytes");

    // Check CRC
    int8_t crc_result = filesys_is_crc_correct(&test_slate);
    TEST_ASSERT(crc_result == FILESYS_OK,
                "CRC should be correct (return FILESYS_OK)");

    // Complete file write (should succeed with correct CRC)
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK,
                "complete_file_write should succeed with correct CRC");

    LOG_DEBUG("=== Test PASSED: CRC Verification - Correct CRC ===\n");
    return 0;
}

// ============================================================================
// Test 13: CRC verification - incorrect CRC
// ============================================================================
int filesys_test_crc_incorrect_should_fail()
{
    LOG_DEBUG("=== Test: CRC Verification - Incorrect CRC ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "IC";
    // Intentionally wrong CRC
    FILESYS_BUFFERED_FILE_CRC_T wrong_crc = 0xDEADBEEF;

    int8_t code = filesys_start_file_write(&test_slate, fname, 64, wrong_crc,
                                           &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    uint8_t buffer[64];
    for (uint8_t i = 0; i < 64; i++)
        buffer[i] = i;

    code = filesys_write_data_to_buffer(&test_slate, buffer, 64, 0);
    TEST_ASSERT(code == FILESYS_OK, "write_data_to_buffer should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 64);
    TEST_ASSERT(code == FILESYS_OK,
                "write_buffer_to_mram should write 64 bytes");

    // Check CRC - should fail
    int8_t crc_result = filesys_is_crc_correct(&test_slate);
    TEST_ASSERT(crc_result == FILESYS_ERR_CRC_MISMATCH,
                "CRC should be incorrect (return FILESYS_ERR_CRC_MISMATCH)");

    // Complete file write should fail due to CRC mismatch
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(
        code == FILESYS_ERR_CRC_MISMATCH,
        "complete_file_write should fail with FILESYS_ERR_CRC_MISMATCH");

    LOG_DEBUG("=== Test PASSED: CRC Verification - Incorrect CRC ===\n");
    return 0;
}

// ============================================================================
// Test 14: CRC check - no file being written
// ============================================================================
int filesys_test_crc_no_file_should_fail()
{
    LOG_DEBUG("=== Test: CRC Check - No File Being Written ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    // Try to check CRC without starting a file write
    int8_t crc_result = filesys_is_crc_correct(&test_slate);
    TEST_ASSERT(
        crc_result == FILESYS_ERR_NO_FILE_WRITING,
        "CRC check without file should fail with FILESYS_ERR_NO_FILE_WRITING");

    LOG_DEBUG("=== Test PASSED: CRC Check - No File Being Written ===\n");
    return 0;
}

// ============================================================================
// Test 15: Multiple file writes in sequence
// ============================================================================
int filesys_test_multiple_files_success()
{
    LOG_DEBUG("=== Test: Multiple File Writes in Sequence ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    // Write first file
    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname1 = "M1";
    uint8_t buffer1[32];
    for (int i = 0; i < 32; i++)
        buffer1[i] = i;

    // Use a simple CRC (we'll compute it properly for this test data)
    int8_t code =
        filesys_start_file_write(&test_slate, fname1, 32, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "First file start should succeed");

    code = filesys_write_data_to_buffer(&test_slate, buffer1, 32, 0);
    TEST_ASSERT(code == FILESYS_OK, "First file buffer write should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 32);
    TEST_ASSERT(code == FILESYS_OK, "First file MRAM write should succeed");

    // Cancel this file (we don't have the correct CRC)
    code = filesys_cancel_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK, "First file cancel should succeed");

    // Write second file
    FILESYS_BUFFERED_FNAME_STR_T fname2 = "M2";
    uint8_t buffer2[16];
    for (int i = 0; i < 16; i++)
        buffer2[i] = 0xFF - i;

    code = filesys_start_file_write(&test_slate, fname2, 16, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "Second file start should succeed");

    code = filesys_write_data_to_buffer(&test_slate, buffer2, 16, 0);
    TEST_ASSERT(code == FILESYS_OK, "Second file buffer write should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 16);
    TEST_ASSERT(code == FILESYS_OK, "Second file MRAM write should succeed");

    LOG_DEBUG("=== Test PASSED: Multiple File Writes in Sequence ===\n");
    return 0;
}

// ============================================================================
// Test 16: Blocks left calculation
// ============================================================================
int filesys_test_blocks_left_calculation_success()
{
    LOG_DEBUG("=== Test: Blocks Left Calculation ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left_1, blocks_left_2;
    FILESYS_BUFFERED_FNAME_STR_T fname = "BL";

    // Get initial filesystem size
    lfs_ssize_t initial_fs_size = lfs_fs_size(&test_slate.lfs);
    TEST_ASSERT(initial_fs_size >= 0, "Should get valid fs size");

    // Start a file write and check blocks left
    int8_t code =
        filesys_start_file_write(&test_slate, fname, 1024, 0x0, &blocks_left_1);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // Blocks left should be: block_count - current_fs_size -
    // blocks_needed_for_file For a 1024 byte file with 1024 byte blocks, we
    // need 1 block
    lfs_ssize_t expected_blocks_left =
        FILESYS_BLOCK_COUNT - initial_fs_size - 1;
    TEST_ASSERT(blocks_left_1 == expected_blocks_left,
                "Blocks left calculation should be correct");

    LOG_DEBUG("=== Test PASSED: Blocks Left Calculation ===\n");
    return 0;
}

// ============================================================================
// Test 17: Multi-chunk write
// ============================================================================
int filesys_test_multi_chunk_write_success()
{
    LOG_DEBUG("=== Test: Multi-Chunk Write ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "MC";

    // Start file write for a larger file (will need multiple buffer writes)
    int8_t code =
        filesys_start_file_write(&test_slate, fname, 128, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // First chunk: write 64 bytes
    uint8_t chunk1[64];
    for (int i = 0; i < 64; i++)
        chunk1[i] = i;

    code = filesys_write_data_to_buffer(&test_slate, chunk1, 64, 0);
    TEST_ASSERT(code == FILESYS_OK, "First chunk write should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 64);
    TEST_ASSERT(code == FILESYS_OK, "First chunk MRAM write should succeed");

    // Second chunk: write another 64 bytes
    uint8_t chunk2[64];
    for (int i = 0; i < 64; i++)
        chunk2[i] = 64 + i;

    code = filesys_write_data_to_buffer(&test_slate, chunk2, 64, 0);
    TEST_ASSERT(code == FILESYS_OK, "Second chunk write should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 64);
    TEST_ASSERT(code == FILESYS_OK, "Second chunk MRAM write should succeed");

    LOG_DEBUG("=== Test PASSED: Multi-Chunk Write ===\n");
    return 0;
}

// ============================================================================
// Test 18: Write at offset
// ============================================================================
int filesys_test_write_at_offset_success()
{
    LOG_DEBUG("=== Test: Write at Offset ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "OF";

    int8_t code =
        filesys_start_file_write(&test_slate, fname, 64, 0x0, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "start_file_write should succeed");

    // Write at different offsets
    uint8_t data1[16] = {0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA,
                         0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA};
    uint8_t data2[16] = {0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB,
                         0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB, 0xBB};

    // Write first 16 bytes at offset 0
    code = filesys_write_data_to_buffer(&test_slate, data1, 16, 0);
    TEST_ASSERT(code == FILESYS_OK, "Write at offset 0 should succeed");

    // Write next 16 bytes at offset 32 (leaving a gap)
    code = filesys_write_data_to_buffer(&test_slate, data2, 16, 32);
    TEST_ASSERT(code == FILESYS_OK, "Write at offset 32 should succeed");

    // Verify data is in the buffer at the correct positions
    for (int i = 0; i < 16; i++)
    {
        TEST_ASSERT(test_slate.filesys_buffer[i] == 0xAA,
                    "Data at offset 0 should be 0xAA");
        TEST_ASSERT(test_slate.filesys_buffer[32 + i] == 0xBB,
                    "Data at offset 32 should be 0xBB");
    }

    LOG_DEBUG("=== Test PASSED: Write at Offset ===\n");
    return 0;
}

// ============================================================================
// Test 19: Multiple file writes in sequence, committing both
// ============================================================================
int filesys_test_multiple_files_commit_success()
{
    LOG_DEBUG("=== Test: Multiple File Writes in Sequence ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    // Write first file
    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname1 = "M1";
    uint8_t buffer1[32];
    for (int i = 0; i < 32; i++)
        buffer1[i] = i;

    // Generated with zlib.crc32(bytes(i for i in range(32))) in Python
    int8_t code = filesys_start_file_write(&test_slate, fname1, 32, 2435219082,
                                           &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "First file start should succeed");

    code = filesys_write_data_to_buffer(&test_slate, buffer1, 32, 0);
    TEST_ASSERT(code == FILESYS_OK, "First file buffer write should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 32);
    TEST_ASSERT(code == FILESYS_OK, "First file MRAM write should succeed");

    // Complete this file
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK, "First file complete should succeed");

    // Write second file
    FILESYS_BUFFERED_FNAME_STR_T fname2 = "M2";
    uint8_t buffer2[16];
    for (int i = 0; i < 16; i++)
        buffer2[i] = 0xFF - i;

    // Generated with zlib.crc32(bytes(0xFF - i for i in range(16))) in Python
    code = filesys_start_file_write(&test_slate, fname2, 16, 499544007,
                                    &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "Second file start should succeed");

    code = filesys_write_data_to_buffer(&test_slate, buffer2, 16, 0);
    TEST_ASSERT(code == FILESYS_OK, "Second file buffer write should succeed");

    code = filesys_write_buffer_to_mram(&test_slate, 16);
    TEST_ASSERT(code == FILESYS_OK, "Second file MRAM write should succeed");

    // Complete second file
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK, "Second file complete should succeed");

    LOG_DEBUG("=== Test PASSED: Multiple File Writes in Sequence ===\n");
    return 0;
}

// ============================================================================
// Test 20: Write really really long file (still fits in filesystem) to test
// CRC32 calculation over multiple buffer writes
// ============================================================================
int filesys_test_write_long_file_crc32_success()
{
    LOG_DEBUG("=== Test: Write Really Long File with CRC32 ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    // Write first file
    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "M1";
    uint8_t buffer[200000]; // Random very large number of bytes

    for (int i = 0; i < sizeof(buffer); i++)
        buffer[i] = (i * 7) % 256; // somewhat random data

    // Generated with zlib.crc32(bytes((i * 7) % 256 for i in range(200000))) in
    // Python.
    int8_t code = filesys_start_file_write(&test_slate, fname, sizeof(buffer),
                                           1728936560, &blocks_left);

    TEST_ASSERT(code == FILESYS_OK, "File start should succeed");

    // Write the data in chunks
    code = filesys_test_write_whole_buffer(&test_slate, buffer, sizeof(buffer));
    TEST_ASSERT(code == FILESYS_OK, "File buffer writes should succeed");

    // Complete this file
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK, "File complete should succeed");

    LOG_DEBUG("=== Test PASSED: Write Really Long File with CRC32 ===\n");
    return 0;
}

// ============================================================================
// Test 21: Try to write a file that won't fit in the filesystem
// ============================================================================
int filesys_test_file_too_large_should_fail()
{
    LOG_DEBUG("=== Test: File Too Large for Filesystem ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname = "BG";

    // Try to write a file larger than the entire filesystem
    FILESYS_BUFFERED_FILE_LEN_T file_size =
        FILESYS_BLOCK_COUNT * FILESYS_BLOCK_SIZE + 10000;

    int8_t code = filesys_start_file_write(&test_slate, fname, file_size, 0x0,
                                           &blocks_left);

    TEST_ASSERT(code == FILESYS_ERR_NOT_ENOUGH_SPACE,
                "Should fail with not enough space error");
    TEST_ASSERT(blocks_left < 0,
                "Blocks left should be negative when insufficient space");

    LOG_DEBUG("=== Test PASSED: File Too Large for Filesystem ===\n");
    return 0;
}

// ============================================================================
// Test 22: Write one file successfully, then run out of space on second file
// ============================================================================
int filesys_test_second_file_out_of_space_should_fail()
{
    LOG_DEBUG("=== Test: Second File Runs Out of Space ===\n");

    slate_t test_slate;
    if (filesys_test_setup_clean_filesystem(&test_slate) < 0)
        return -1;

    lfs_ssize_t initial_fs_size = lfs_fs_size(&test_slate.lfs);

    lfs_ssize_t blocks_left;
    FILESYS_BUFFERED_FNAME_STR_T fname1 = "F1";
    FILESYS_BUFFERED_FNAME_STR_T fname2 = "F2";

    // Write first file that takes up most of the filesystem
    FILESYS_BUFFERED_FILE_LEN_T file1_size =
        FILESYS_BLOCK_COUNT * FILESYS_BLOCK_SIZE - 300000; // Leave ~60KB free

    uint8_t large_buffer[file1_size];
    for (int i = 0; i < file1_size; i++)
        large_buffer[i] = (i * 3) % 256;

    // Note: CRC32 is computed based on the fact that FILESYS_BLOCK_COUNT *
    // FILESYS_BLOCK_SIZE == 524288. If this is not true, this CRC is invalid!
    TEST_ASSERT(FILESYS_BLOCK_COUNT * FILESYS_BLOCK_SIZE == 524288,
                "Test setup assumption failed: FILESYS_BLOCK_COUNT * "
                "FILESYS_BLOCK_SIZE must equal 524288 for this test");

    // Generated with zlib.crc32(bytes((i * 3) % 256 for i in range(524288 -
    // 60000))) in Python
    int8_t code = filesys_start_file_write(&test_slate, fname1, file1_size,
                                           3631967889, &blocks_left);
    TEST_ASSERT(code == FILESYS_OK, "First file start should succeed");
    TEST_ASSERT(blocks_left >= 0, "Should have space for first file");

    // Write the data in chunks
    for (FILESYS_BUFFER_SIZE_T i = 0; i < file1_size; i += FILESYS_BUFFER_SIZE)
    {
        const FILESYS_BUFFER_SIZE_T to_write =
            (file1_size - i) < FILESYS_BUFFER_SIZE ? (file1_size - i)
                                                   : FILESYS_BUFFER_SIZE;
        LOG_DEBUG("Writing %u bytes at offset %u\n", to_write, i);

        int8_t code = filesys_write_data_to_buffer(
            &test_slate, large_buffer + i, to_write, 0);
        TEST_ASSERT(code == FILESYS_OK, "File buffer write should succeed");

        code = filesys_write_buffer_to_mram(&test_slate, to_write);
        TEST_ASSERT(code == FILESYS_OK,
                    "File buffer to MRAM write should succeed");
    }

    // Make sure we can read back the first file correctly
    // uint8_t read_buffer[file1_size];
    // lfs_file_t file;
    // int err = lfs_file_opencfg(&test_slate.lfs, &file, fname1, LFS_O_RDONLY,
    //                            &filesys_lfs_file_cfg);
    // LOG_DEBUG("Opened first file for reading, err=%d\n", err);
    // TEST_ASSERT(err == 0, "Should open first file for reading");
    // lfs_ssize_t read_bytes =
    //     lfs_file_read(&test_slate.lfs, &file, read_buffer, file1_size);
    // LOG_DEBUG("Read back %d bytes from first file\n", read_bytes);
    // TEST_ASSERT(read_bytes == file1_size, "Should read back full first
    // file"); TEST_ASSERT(memcmp(large_buffer, read_buffer, file1_size) == 0,
    //             "Read back data should match written data");
    // lfs_file_close(&test_slate.lfs, &file);

    // Complete first file
    code = filesys_complete_file_write(&test_slate);
    TEST_ASSERT(code == FILESYS_OK, "First file complete should succeed");

    // Now try to write a second file that won't fit in remaining space
    // Try to write 100KB when we only have ~62KB left
    FILESYS_BUFFERED_FILE_LEN_T file2_size = 100000;
    code = filesys_start_file_write(&test_slate, fname2, file2_size, 0x0,
                                    &blocks_left);

    TEST_ASSERT(code == FILESYS_ERR_NOT_ENOUGH_SPACE,
                "Second file should fail with not enough space");
    TEST_ASSERT(blocks_left < 0,
                "Blocks left should be negative when insufficient space");

    LOG_DEBUG("=== Test PASSED: Second File Runs Out of Space ===\n");
    return 0;
}

// ============================================================================
// Main test runner
// ============================================================================
int main()
{
    LOG_DEBUG("========================================\n");
    LOG_DEBUG("Starting Filesys Test Suite\n");
    LOG_DEBUG("========================================\n");

    int result;
    int tests_passed = 0;
    int tests_failed = 0;

    // Define test functions
    struct
    {
        int (*test_func)(void);
        const char *name;
    } tests[] = {
        // {filesys_test_write_readback_success, "Write and Readback"},
        // {filesys_test_initialize_reformat_success, "Initialize and
        // Reformat"},
        // {filesys_test_start_file_write_already_writing_should_fail,
        //  "Start File Write - Already Writing"},
        // {filesys_test_write_data_to_buffer_bounds_should_fail,
        //  "Write Data to Buffer - Bounds Checking"},
        // {filesys_test_write_data_to_buffer_when_no_file_started_should_fail,
        //  "Write Data to Buffer - No File"},
        // {filesys_test_write_buffer_to_mram_when_no_file_started_should_fail,
        //  "Write Buffer to MRAM - No File"},
        // {filesys_test_write_buffer_to_mram_clean_buffer_success,
        //  "Write Buffer to MRAM - Clean Buffer"},
        // {filesys_test_complete_file_write_dirty_buffer_success,
        //  "Complete File Write - Dirty Buffer"},
        // {filesys_test_cancel_file_write_success, "Cancel File Write"},
        // {filesys_test_cancel_file_write_no_file_should_fail,
        //  "Cancel File Write - No File"},
        // {filesys_test_clear_buffer_success, "Clear Buffer"},
        // {filesys_test_crc_correct_success, "CRC Verification - Correct"},
        // {filesys_test_crc_incorrect_should_fail,
        //  "CRC Verification - Incorrect"},
        // {filesys_test_crc_no_file_should_fail, "CRC Check - No File"},
        // {filesys_test_multiple_files_success, "Multiple File Writes"},
        // {filesys_test_blocks_left_calculation_success,
        //  "Blocks Left Calculation"},
        // {filesys_test_multi_chunk_write_success, "Multi-Chunk Write"},
        // {filesys_test_write_at_offset_success, "Write at Offset"},
        // {filesys_test_multiple_files_commit_success,
        //  "Multiple File Writes Committed"},
        {filesys_test_write_long_file_crc32_success,
         "Write Really Long File with CRC32"},
        // {filesys_test_file_too_large_should_fail,
        //  "File Too Large for Filesystem"},
        // {filesys_test_second_file_out_of_space_should_fail,
        //  "Second File Runs Out of Space"},
    };

    int num_tests = sizeof(tests) / sizeof(tests[0]);

    for (int i = 0; i < num_tests; i++)
    {
        LOG_DEBUG("\n--- Running Test %d/%d: %s ---\n", i + 1, num_tests,
                  tests[i].name);
        result = tests[i].test_func();
        if (result == 0)
        {
            tests_passed++;
            LOG_DEBUG("--- Test %d PASSED ---\n", i + 1);
        }
        else
        {
            tests_failed++;
            LOG_ERROR("--- Test %d FAILED ---\n", i + 1);
        }
    }

    LOG_DEBUG("\n========================================\n");
    LOG_DEBUG("Test Suite Complete\n");
    LOG_DEBUG("Passed: %d / %d\n", tests_passed, num_tests);
    LOG_DEBUG("Failed: %d / %d\n", tests_failed, num_tests);
    LOG_DEBUG("========================================\n");

    if (tests_failed > 0)
    {
        LOG_ERROR("SOME TESTS FAILED!\n");
        return -1;
    }

    LOG_DEBUG("All Filesys tests passed!\n");
    return 0;
}
