name: C/C++ Tests

on:
  push:
    paths:
      - "src/**"
      - "bzl/**"
      - "BUILD.bazel"
      - ".bazelrc"
      - ".github/workflows/*.yaml"
  pull_request:
    paths:
      - "src/**"
      - "bzl/**"
      - "BUILD.bazel"
      - ".bazelrc"
      - ".github/workflows/*.yaml"
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Project
        run: ./configure.sh

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@v1
        with:
          disk-cache: true
          repository-cache: true

      - name: Run all tests
        run: bazel test //src/... --test_output=errors

      - name: Archive test visualization logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-visualization-logs
          path: |
            bazel-testlogs/**/*_viz.json
            bazel-bin/**/*_viz.json
