name: C/C++ Tests

on:
  push:
    paths:
      - "src/**"
      - "bzl/**"
      - "BUILD.bazel"
      - ".bazelrc"
      - ".github/workflows/*.yaml"
  pull_request:
    paths:
      - "src/**"
      - "bzl/**"
      - "BUILD.bazel"
      - ".bazelrc"
      - ".github/workflows/*.yaml"
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Project
        run: ./configure.sh

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel-tests-${{ hashFiles('.bazelrc', 'MODULE.bazel', 'bzl/**') }}
          restore-keys: |
            bazel-tests-
            bazel-

      - name: Run all tests
        run: bazel test //src/... --config=tests --test_output=errors

      - name: Archive test visualization logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-visualization-logs
          path: |
            bazel-testlogs/**/*_viz.json
            bazel-bin/**/*_viz.json
